<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DFEV0VQ" failures="1" tests="4" name="REST API POST Test" time="0.7" errors="0" timestamp="18 Jan 2021 14:03:19 GMT">
  <testcase classname="POSTTest" name="validPostTest" time="0.218"/>
  <testcase classname="POSTTest" name="InvalidIdPostTest" time="0.186"/>
  <testcase classname="POSTTest" name="RepeatedIDPostTest" time="0.166"/>
  <testcase classname="POSTTest" name="InvalidNamePostTest" time="0.074">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;ERROR&amp;gt; but was:&amp;lt;SUCCESS&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at POSTTest.InvalidNamePostTest(POSTTest.java:133)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase>
</testsuite>
