<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="8" passed="6" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-18T15:41:59Z" name="Suite1" finished-at="2021-01-18T15:42:01Z" duration-ms="2543">
    <groups>
    </groups>
    <test started-at="2021-01-18T15:41:59Z" name="Nopackage" finished-at="2021-01-18T15:42:01Z" duration-ms="2543">
      <class name="POSTTest">
        <test-method signature="validPostTest()[pri:1, instance:POSTTest@68c72235]" started-at="2021-01-18T15:41:59Z" name="validPostTest" finished-at="2021-01-18T15:41:59Z" duration-ms="199" status="PASS">
        </test-method>
        <test-method signature="InvalidIdPostTest()[pri:2, instance:POSTTest@68c72235]" started-at="2021-01-18T15:41:59Z" name="InvalidIdPostTest" finished-at="2021-01-18T15:41:59Z" duration-ms="409" status="PASS">
        </test-method>
        <test-method signature="RepeatedIDPostTest()[pri:3, instance:POSTTest@68c72235]" started-at="2021-01-18T15:41:59Z" name="RepeatedIDPostTest" finished-at="2021-01-18T15:42:00Z" duration-ms="163" status="PASS">
        </test-method>
        <test-method signature="InvalidNamePostTest()[pri:10, instance:POSTTest@68c72235]" started-at="2021-01-18T15:42:00Z" name="InvalidNamePostTest" finished-at="2021-01-18T15:42:00Z" duration-ms="84" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<ERROR> but was:<SUCCESS>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<ERROR> but was:<SUCCESS>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at POSTTest.InvalidNamePostTest(POSTTest.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
      <class name="DeleteTest">
        <test-method is-config="true" signature="setData()[pri:0, instance:DeleteTest@6b8ca3c8]" started-at="2021-01-18T15:41:59Z" name="setData" finished-at="2021-01-18T15:41:59Z" duration-ms="114" status="PASS">
        </test-method>
        <test-method is-config="true" signature="setData()[pri:0, instance:POSTTest@68c72235]" started-at="2021-01-18T15:41:59Z" name="setData" finished-at="2021-01-18T15:41:59Z" duration-ms="109" status="PASS">
        </test-method>
        <test-method signature="testingDeleteWithID()[pri:1, instance:DeleteTest@6b8ca3c8]" started-at="2021-01-18T15:42:00Z" name="testingDeleteWithID" finished-at="2021-01-18T15:42:00Z" duration-ms="84" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:365)
	at org.testng.Assert.assertEquals(Assert.java:375)
	at DeleteTest.testingDeleteWithID(DeleteTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method signature="testingDeleteAll()[pri:2, instance:DeleteTest@6b8ca3c8]" started-at="2021-01-18T15:42:00Z" name="testingDeleteAll" finished-at="2021-01-18T15:42:00Z" duration-ms="101" status="PASS">
        </test-method>
        <test-method signature="testingDeleteAllEmpty()[pri:3, instance:DeleteTest@6b8ca3c8]" started-at="2021-01-18T15:42:00Z" name="testingDeleteAllEmpty" finished-at="2021-01-18T15:42:00Z" duration-ms="131" status="PASS">
        </test-method>
        <test-method signature="testingDeleteWithdoesntExistID()[pri:6, instance:DeleteTest@6b8ca3c8]" started-at="2021-01-18T15:42:00Z" name="testingDeleteWithdoesntExistID" finished-at="2021-01-18T15:42:01Z" duration-ms="1124" status="PASS">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
